version: '3.8'

services:
  vm-operator:
    build:
      context: ../../
      dockerfile: docker/vm-operator/Dockerfile
    container_name: megalopolis-vm-operator
    ports:
      - "8082:8082"
    volumes:
      # Mount tart binary from host (required for VM operations)
      - "../../tart-binary:/app/bin/tart-binary:ro"
      # Mount tart VM storage directory  
      - "${HOME}/.tart:/home/vmoperator/.tart:rw"
      # Mount logs directory
      - "./logs:/app/logs:rw"
    environment:
      - PATH=/app/bin:$PATH
      - TART_HOME=/home/vmoperator/.tart
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8082/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - megalopolis

networks:
  megalopolis:
    driver: bridge