apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchard-data
  namespace: orchard-system
  labels:
    app: orchard-controller
    app.kubernetes.io/name: orchard
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: megalopolis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Use Kind's default storage class
  storageClassName: standard