apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-api-bridge-config
  namespace: orchard-system
  labels:
    app: vm-api-bridge
    app.kubernetes.io/name: orchard
    app.kubernetes.io/component: api-bridge
    app.kubernetes.io/part-of: megalopolis
data:
  config.yaml: |
    # VM API Bridge Configuration
    api:
      listen_addr: "0.0.0.0:8081"
      cors_enabled: true
      cors_origins:
        - "http://localhost:*"
        - "http://127.0.0.1:*"
    
    # Orchard controller endpoint
    orchard:
      endpoint: "http://orchard-controller:8080"
      timeout: "30s"
    
    # VM management settings
    vm_management:
      tart_binary_path: "/usr/local/bin/tart"
      default_vm_configs_path: "/etc/vm-configs"
      max_concurrent_operations: 3
    
    # Logging
    logging:
      level: "info"
      format: "json"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-api-bridge
  namespace: orchard-system
  labels:
    app: vm-api-bridge
    app.kubernetes.io/name: orchard
    app.kubernetes.io/component: api-bridge
    app.kubernetes.io/part-of: megalopolis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-api-bridge
  template:
    metadata:
      labels:
        app: vm-api-bridge
    spec:
      serviceAccountName: orchard-controller
      containers:
      - name: vm-api-bridge
        # This would be a custom bridge service
        # For now, we'll use a simple nginx to serve static content
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: BRIDGE_CONFIG_PATH
          value: "/etc/config/config.yaml"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: vm-configs
          mountPath: /etc/vm-configs
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: vm-api-bridge-config
      - name: vm-configs
        configMap:
          name: vm-configs
          optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: vm-api-bridge
  namespace: orchard-system
  labels:
    app: vm-api-bridge
    app.kubernetes.io/name: orchard
    app.kubernetes.io/component: api-bridge
    app.kubernetes.io/part-of: megalopolis
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: vm-api-bridge