apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vms.megalopolis.io
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: crd
spec:
  group: megalopolis.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "Name of the VM"
              baseImage:
                type: string
                description: "Base image for the VM"
              resources:
                type: object
                properties:
                  memory:
                    type: string
                    description: "Memory allocation (e.g., '4096')"
                  cpu:
                    type: string
                    description: "CPU allocation (e.g., '2')"
                  disk:
                    type: string
                    description: "Disk size (e.g., '40')"
              settings:
                type: object
                properties:
                  sshEnabled:
                    type: boolean
                    description: "Enable SSH access"
                  vncEnabled:
                    type: boolean
                    description: "Enable VNC access"
                  autoStart:
                    type: boolean
                    description: "Auto-start VM on creation"
              network:
                type: object
                properties:
                  mode:
                    type: string
                    enum: ["bridged", "host", "nat"]
                    description: "Network mode"
                  portForwards:
                    type: array
                    items:
                      type: string
                    description: "Port forwarding rules"
            required:
            - name
            - baseImage
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["pending", "creating", "running", "stopped", "error"]
                description: "Current phase of the VM"
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              ipAddress:
                type: string
                description: "IP address of the VM"
              readiness:
                type: string
                enum: ["ready", "booting", "ssh-pending", "not-ready"]
                description: "Readiness status of the VM"
              lastUpdated:
                type: string
                format: date-time
                description: "Last update timestamp"
  scope: Namespaced
  names:
    plural: vms
    singular: vm
    kind: VM
    shortNames:
    - vm
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmconfigs.megalopolis.io
  labels:
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: crd
spec:
  group: megalopolis.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: object
                description: "Template for VM creation"
                properties:
                  baseImage:
                    type: string
                  resources:
                    type: object
                    properties:
                      memory:
                        type: string
                      cpu:
                        type: string
                      disk:
                        type: string
                  settings:
                    type: object
                    properties:
                      sshEnabled:
                        type: boolean
                      vncEnabled:
                        type: boolean
                      autoStart:
                        type: boolean
              description:
                type: string
                description: "Description of the VM config"
            required:
            - template
          status:
            type: object
            properties:
              ready:
                type: boolean
                description: "Whether the config is ready for use"
  scope: Namespaced
  names:
    plural: vmconfigs
    singular: vmconfig
    kind: VMConfig
    shortNames:
    - vmcfg