apiVersion: v1
kind: Service
metadata:
  name: vm-operator
  namespace: orchard-system
  labels:
    app: vm-operator
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: vm-operator
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vm-operator
  namespace: orchard-system
  labels:
    app: vm-operator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: vm-operator.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vm-operator
            port:
              number: 8082
  - http:
      paths:
      - path: /vm-api
        pathType: Prefix
        backend:
          service:
            name: vm-operator
            port:
              number: 8082