apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator
  namespace: orchard-system
  labels:
    app: vm-operator
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-operator
  labels:
    app: vm-operator
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["megalopolis.io"]
  resources: ["vms", "vmconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["megalopolis.io"]
  resources: ["vms/status", "vmconfigs/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-operator
  labels:
    app: vm-operator
    app.kubernetes.io/name: vm-operator
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vm-operator
subjects:
- kind: ServiceAccount
  name: vm-operator
  namespace: orchard-system